/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

    // Escribir una interface perimetrable con un metodo calcularPerimetro()
interface Perimetrable {
    fun calcularPerimetro(): Double
}

    // Escribir una clase Rectangulo que implemente la interface Perimetrable
class Rectangulo(private val base: Double, private val altura: Double) : Perimetrable {
    override fun calcularPerimetro(): Double = 2 * (base + altura)
}

    // Escribir una clase Circulo que implemente la interface Perimetrable
class Circulo(private val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double = 2 * Math.PI * radio
}


fun main() {
    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")


    // Crear una lista con un objeto de cada clase y mostrar el perimetro de cada uno
    val figuras: List<Perimetrable> = listOf(
        Rectangulo(10.0, 5.0),
        Circulo(7.0)
    )

    figuras.forEach { figura ->
        println("Perímetro de ${figura::class.simpleName}: ${figura.calcularPerimetro()}")
    }
}




   
